version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y zip unzip
  build:
    commands:
      - echo Packaging application files...
      - zip -r lamp-app.zip . -x "*.git*"

artifacts:
  files:
    - lamp-app.zip
